import {COLORS,SEVERITIES,label,filterAlerts,dateRangeError,healthState,mapSeverity,sourceUrl,displayTime} from './lib.js';
import {fetchJSON,recentProvider,historyProvider} from './history.js';
const $=id=>document.getElementById(id);
const el=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;};
const state={latest:[],scope:'latest',offset:0,rows:[],health:healthState(),providers:{recent:recentProvider()},request:0,latestFailed:false};
let map,geoLayer;
const filters=()=>Object.fromEntries(new FormData($('filters')));
const languageNames={en:'English',si:'සිංහල',ta:'தமிழ்',unknown:'Unknown language'};
function officialLink(url,text,className){const safe=sourceUrl(url);if(!safe)return el('span','Official source link unavailable',className);const a=el('a',text,className);a.href=safe;a.target='_blank';a.rel='noopener noreferrer';return a;}
function options(id,values){for(const value of values)$(id).append(new Option(label(value),value));}
options('hazard',['heavy_rain','flood','river_flood','landslide','lightning','strong_wind','high_waves','rough_sea','cyclone','drought','general_weather','other']);options('severity',SEVERITIES);options('document_type',['situation','weather','river_flood','landslide']);
for(const [severity,color] of Object.entries(COLORS)){const item=el('span');const dot=el('i');dot.style.background=color;item.append(dot,document.createTextNode(severity==='no_coverage'?'No coverage / no match':label(severity)));$('legend').append(item);}
function health(m){state.health=healthState(m);$('health').dataset.kind=state.health.kind;$('health-label').textContent={success:'Collection up to date',partial:'Collection incomplete',error:'Collection failed',stale:'Collection is stale',source_stale:'Source documents are stale',never_run:'Coverage unavailable'}[state.health.kind];$('health-message').textContent=state.health.message;$('last-success').textContent=displayTime(m.last_successful_scrape);$('last-document').textContent=displayTime(m.last_dmc_document_seen);const box=$('health-details');box.replaceChildren(el('p','Latest run: '+displayTime(m.last_run)));for(const field of ['documents_checked','new_documents','failed_documents','download_failures','parsing_failures','duplicate_count','unknown_language_count'])box.append(el('p',label(field)+': '+(m[field]??'Not available')));for(const [category,status] of Object.entries(m.category_status||{}))box.append(el('p',label(category)+': '+(typeof status==='object'?JSON.stringify(status):status)));for(const error of m.errors||[])box.append(el('p',typeof error==='object'?JSON.stringify(error):String(error)));}
function showDetails(a){$('dialog-title').textContent=a.title||'Untitled report';const content=$('dialog-content');content.replaceChildren(officialLink(a.source_pdf,'Read the official source PDF ↗','detail-source'));
 const official=el('section',undefined,'detail-section');official.append(el('h3','Official source metadata'));const dl=el('dl');const pairs=[['Source','Disaster Management Centre'],['Document type',label(a.document_type)],['Published date',a.official?.report_date||'Not available'],['Published time',a.official?.report_time||'Not available'],['Issue time',displayTime(a.issued_at)],['Valid from',displayTime(a.valid_from)],['Valid until',displayTime(a.valid_until)]];for(const [key,value] of pairs)dl.append(el('dt',key),el('dd',value));official.append(dl,officialLink(a.source_page,'View official listing page ↗'));content.append(official);
 const extraction=el('section',undefined,'detail-section');extraction.append(el('h3','Automated extraction'),el('p','These fields are inferred from the document. Districts are mentions, not confirmed affected areas. Verify the original PDF before making decisions.','extraction-note'));for(const [key,value] of [['Hazards',(a.hazards||[a.hazard]).map(label).join(', ')],['Severity',label(a.severity)],['Severity evidence',(a.extraction?.severity_evidence||[]).join?.(', ')||a.extraction?.severity_evidence||'No explicit evidence'],['Severity reason',a.extraction?.severity_reason||'Not available'],['District mentions',(a.districts||[]).join(', ')||'No district names detected'],['Province mentions',(a.provinces||[]).join(', ')||'None detected'],['Language',(languageNames[a.language]||'Unknown')+'; confidence '+(Number.isFinite(a.language_confidence)?Math.round(a.language_confidence*100)+'%':'unavailable')],['Language reason',a.language_reason||'Not available'],['Extraction status',a.extraction?.status||'Not available'],['Rules version',a.extraction?.rules_version||'Not available'],['Processed',displayTime(a.processed_at)]]){const p=el('p');p.append(el('strong',key+': '),document.createTextNode(String(value)));extraction.append(p);}extraction.append(el('h3','Extracted text excerpt'),el('p',a.summary||'No readable text was extracted. Open the official PDF.'));content.append(extraction);$('report-dialog').showModal();}
$('dialog-close').addEventListener('click',()=>$('report-dialog').close());$('report-dialog').addEventListener('click',e=>{if(e.target===$('report-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
function renderCards(){const list=$('report-list');list.replaceChildren();$('report-count').textContent=String(state.rows.length);if(!state.rows.length){const empty=el('div',undefined,'empty');empty.append(el('h3','No recent matching report'),el('p',state.scope==='history'?'No archived reports match these filters. Try a wider date range or another district.':'Try another district, broaden your filters, or open the recent reports. Absence of a report does not mean safe.'));list.append(empty);return;}
 for(const a of state.rows){const card=el('article',undefined,'report-card');const meta=el('div',undefined,'report-meta');const badge=el('span',label(a.severity),'severity');badge.style.setProperty('--severity',COLORS[a.severity]||COLORS.unknown);meta.append(badge,el('span',label(a.document_type)),el('span','· '+(languageNames[a.language]||'Unknown language')));const title=el('h3',a.title||'Untitled report');title.lang=['en','si','ta'].includes(a.language)?a.language:'en';card.append(meta,title,el('p','Issued '+displayTime(a.issued_at),'report-time'),el('p',a.summary||'No readable excerpt. Read the official PDF for the complete report.','report-summary'),el('p','District mentions: '+((a.districts||[]).join(', ')||'None detected'),'district-tags'));const actions=el('div',undefined,'card-actions');const details=el('button','Report details');details.type='button';details.addEventListener('click',()=>showDetails(a));actions.append(officialLink(a.source_pdf,'Official PDF ↗'),details);card.append(actions);list.append(card);}}
function updateMap(){if(!geoLayer)return;const rows=filterAlerts(state.latest,filters());geoLayer.eachLayer(layer=>{const district=layer.feature.properties.name;const matches=rows.filter(a=>a.districts?.includes(district));const level=mapSeverity(matches,state.health.muted||state.latestFailed);const selected=filters().district===district;layer.setStyle({fillColor:COLORS[level],fillOpacity:.88,color:selected?'#143449':'#ffffff',weight:selected?3:1.2});const description=district+': '+(level==='no_coverage'?(state.health.muted||state.latestFailed?'current coverage unavailable':'no recent matching report'):matches.length+' report'+(matches.length===1?'':'s')+'; '+label(level)+' extracted');const tooltip=el('span',description);layer.setTooltipContent(tooltip);const path=layer.getElement();if(path)path.setAttribute('aria-label',description+'; select district');});$('map-status').textContent=state.health.muted||state.latestFailed?'Current coverage unavailable · map shown in gray':rows.length+' matching reports in the latest 72-hour window';}
function initMap(geometry){if(!window.L){$('map-status').textContent='Map library could not load. Use the district filter to browse reports.';return;}map=L.map('map',{zoomControl:true,zoomSnap:0.1,zoomDelta:0.5,scrollWheelZoom:false,attributionControl:true,dragging:true});geoLayer=L.geoJSON(geometry,{onEachFeature(feature,layer){layer.bindTooltip(el('span',feature.properties.name));layer.on('click',()=>selectDistrict(feature.properties.name));layer.on('add',()=>{const path=layer.getElement();if(path){path.setAttribute('tabindex','0');path.setAttribute('role','button');path.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();selectDistrict(feature.properties.name);}});}});}}).addTo(map);map.fitBounds(geoLayer.getBounds(),{padding:[25,15]});map.setMinZoom(map.getZoom()-1);map.setMaxZoom(map.getZoom()+3);new ResizeObserver(()=>{map.invalidateSize();map.setMinZoom(0);map.fitBounds(geoLayer.getBounds(),{padding:[25,15]});map.setMinZoom(map.getZoom()-1);map.setMaxZoom(map.getZoom()+3);}).observe($('map'));map.attributionControl.addAttribution('Boundaries: © OpenStreetMap / Wambacher · ODbL');$('map-reset').addEventListener('click',()=>map.fitBounds(geoLayer.getBounds(),{padding:[25,15]}));updateMap();}
function selectDistrict(name){$('district').value=name;refresh();}
async function refresh(more=false){const id=++state.request;const f=filters();const error=dateRangeError(f);$('filter-error').hidden=!error;$('filter-error').textContent=error;updateMap();$('load-more').hidden=true;if(error){$('feed-status').textContent=error;state.rows=[];renderCards();return;}if(!more){state.offset=0;state.rows=[];$('report-list').replaceChildren();$('report-count').textContent='—';}else state.offset+=50;$('feed-status').textContent='Loading reports…';try{let result;if(state.scope==='latest'){if(state.latestFailed)throw new Error('Latest report data could not be loaded. Reload the page or consult the official DMC website.');result={rows:filterAlerts(state.latest,f),hasMore:false};}else result=await state.providers[state.scope].search(f,state.offset);if(id!==state.request)return;state.rows=more?[...state.rows,...result.rows]:result.rows;renderCards();$('load-more').hidden=!result.hasMore;$('feed-status').textContent='';}catch(e){if(id!==state.request)return;if(more)state.offset-=50;$('feed-status').textContent=state.scope==='history'?'Historical archive is unavailable. Latest and recent reports remain available. '+e.message:e.message;if(more)$('load-more').hidden=false;$('report-count').textContent=String(state.rows.length);}}
$('filters').addEventListener('change',()=>refresh());$('filters').addEventListener('submit',e=>{e.preventDefault();refresh();});$('filters').addEventListener('reset',()=>setTimeout(()=>refresh(),0));$('load-more').addEventListener('click',()=>refresh(true));
for(const button of document.querySelectorAll('[data-scope]'))button.addEventListener('click',()=>{state.scope=button.dataset.scope;for(const tab of document.querySelectorAll('[data-scope]'))tab.setAttribute('aria-pressed',String(tab===button));$('reports-title').textContent={latest:'Latest reports',recent:'Recent reports',history:'Historical archive'}[state.scope];$('scope-note').textContent=state.scope==='history'?'Search older reports in the public archive, 50 at a time. Archive hazard filtering uses the primary hazard. Missing issue times are excluded by date filters.':'Reports use the source issue time. Documents without an issue time remain in the archive.';refresh();});
async function init(){const results=await Promise.allSettled(['alerts_latest.json','metadata.json','districts.json','districts.geojson','config.json'].map(name=>fetchJSON('./data/'+name)));const [latest,metadata,districts,geometry,config]=results;state.latest=latest.status==='fulfilled'&&Array.isArray(latest.value)?latest.value:[];state.latestFailed=latest.status==='rejected'||!Array.isArray(latest.value);health(metadata.status==='fulfilled'?metadata.value:{status:'error',errors:['Collection metadata could not be loaded.']});if(districts.status==='fulfilled')options('district',districts.value.districts.map(d=>d.name).sort());state.providers.history=historyProvider(config.status==='fulfilled'?config.value.hf_dataset:null);if(geometry.status==='fulfilled')initMap(geometry.value);else $('map-status').textContent='District boundaries are unavailable. Use the district filter to browse reports.';await refresh();}
init();
